### ISSUE TITLE
Add support for extra resources such as users, teams, integrations with the new pingdom API

### ISSUE THREAD

**Issue by shteryana** [Stremio/terraform-provider-pingdom#1]
Pingdom deployed an updated version of their API several months ago, which broke the unofficial github terraform pingdom provider.

An initial somewhat working version of the provider using the v3.1 Pingdom API was created in the [3.1-api branch](https://github.com/Stremio/terraform-provider-pingdom/tree/3.1-api) of this repo. The current code only supports adding checks via the terraform provider.

The work needs to be extended to support adding resources such as users, teams, integrations, etc via the pingdom provider similar to the functionality supported via [Pingdom's API v3.1](https://docs.pingdom.com/api/)

**Comment by barzaka12** [comment]
The API only allows adding checks and maintenance windows. Can only add support for adding maintenance windows.
